/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package overlay;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class OverlayTest {
    @Test
    void appHasADimension() {
        Overlay classUnderTest = new Overlay();
        assertNotNull(classUnderTest.calcDimension(), "app should have a dimension");
    }
}
